name: Build

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check Lint
        run: yarn lint
